### ISSUE TITLE
check on Fathom in code injection 

### ISSUE THREAD

**Issue by davidmooreppf** [yescomment/sl-sludgeline#2]
In code injection, the line mentioning Fathom reads ```<script src="https://cdn.usefathom.com/script.js" data-site="QWNFYHQD" defer></script>```

But on BH Fathom for domain readsludge, nothing doing. Whoopsers. Reckon some traffic should be showing there.

**Comment by davidmooreppf** [comment]
Hmm will be interested in hearing if you updated the line of Fathom code b/c now readsludge domain is showing traffic numbers in BH Fathom.

**Comment by unitof** [comment]
It's been there since launch—it's the `www.`/non-`www.` difference again. However Fathom confusingly hides the www, yet shows both your readsludge.com domains as separate.

During a low-traffic time (so less risk of Thursday's mistakes on my end), would love to finally get that in order and get all your traffic back to `https://readsludge.com`, with no www.

**Comment by unitof** [comment]
Closing since we found cause, but may create new issue/plan to do that DNS change (but more carefully this time).
